#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# say hi on the 9th loop.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
