#!/usr/bin/env bash

# This script kills the process started by the command '7-highlander'.
# Use pgrep to find processes by command line
# '-f' option allows matching against the full command line
# '7-highlander' is the pattern to search for
# Pipe the output of pgrep to kill to terminate the process
# '-9' option is used to forcefully kill the process

kill -9 "$(pgrep -f 7-highlander)"
