#!/usr/bin/env bash
# This script displays the contents of the file `/etc/passwd`.
# Showing only the username, user id, and user home directory path.
# Read each line of the '/etc/passwd' file

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
