#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.

awk '{print $1 " " $9}' apache-access.log

103-dig_the-data 
#!/usr/bin/env bash
# This script parses Apache log files in list format.
#   It groups visitors by IP and HTTP status code.
#   and displays the number of occurrences, IP, and HTTP status
#   code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
