#!/usr/bin/env bash
# This script parses Apache log files in list format,
# displaying the IP and HTTP status code.
# Parse Apache log file and display IP address and HTTP status code

awk '{print $1 " " $9}' apache-access.log

