#!/usr/bin/env bash
# This script iterates from 1 to 10,
displaying different message based on the iteration number:
# - "Encouragement message 1" on the 4th iteration
# - "Encouragement message 2" on the 8th iteration
# - "Default message" for all other iterations
# Initialize a counter variable

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done

